const viewpointChoices = [
  { value: 'unknown', labelId: 'VIEWPOINT_UNKNOWN' },
  { value: 'up', labelId: 'VIEWPOINT_UP' },
  { value: 'down', labelId: 'VIEWPOINT_DOWN' },
  { value: 'front', labelId: 'VIEWPOINT_FRONT' },
  { value: 'left', labelId: 'VIEWPOINT_LEFT' },
  { value: 'back', labelId: 'VIEWPOINT_BACK' },
  { value: 'right', labelId: 'VIEWPOINT_RIGHT' },
  { value: 'upfront', labelId: 'VIEWPOINT_UP_FRONT' },
  { value: 'upback', labelId: 'VIEWPOINT_UP_BACK' },
  { value: 'upleft', labelId: 'VIEWPOINT_UP_LEFT' },
  { value: 'upright', labelId: 'VIEWPOINT_UP_RIGHT' },
  { value: 'downfront', labelId: 'VIEWPOINT_DOWN_FRONT' },
  { value: 'downback', labelId: 'VIEWPOINT_DOWN_BACK' },
  { value: 'downleft', labelId: 'VIEWPOINT_DOWN_LEFT' },
  { value: 'downright', labelId: 'VIEWPOINT_DOWN_RIGHT' },
  { value: 'frontleft', labelId: 'VIEWPOINT_FRONT_LEFT' },
  { value: 'frontright', labelId: 'VIEWPOINT_FRONT_RIGHT' },
  { value: 'backleft', labelId: 'VIEWPOINT_BACK_LEFT' },
  { value: 'backright', labelId: 'VIEWPOINT_BACK_RIGHT' },
  { value: 'upfrontleft', labelId: 'VIEWPOINT_UP_FRONT_LEFT' },
  { value: 'upfrontright', labelId: 'VIEWPOINT_UP_FRONT_RIGHT' },
  { value: 'upbackleft', labelId: 'VIEWPOINT_UP_BACK_LEFT' },
  { value: 'upbackright', labelId: 'VIEWPOINT_UP_BACK_RIGHT' },
  { value: 'downfrontleft', labelId: 'VIEWPOINT_DOWN_FRONT_LEFT' },
  { value: 'downfrontright', labelId: 'VIEWPOINT_DOWN_FRONT_RIGHT' },
  { value: 'downbackleft', labelId: 'VIEWPOINT_DOWN_BACK_LEFT' },
  { value: 'downbackright', labelId: 'VIEWPOINT_DOWN_BACK_RIGHT' },
];

export default viewpointChoices;
